name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

env:
  GO_VERSION: '1.25.1'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Build cross-platform binaries
        env:
          VERSION: ${{ inputs.version }}
          OUTPUT_DIR: out
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          ./scripts/build.sh
          ls -lh out/

      - name: Verify release artifacts exist
        run: |
          test -f out/osdd-linux-amd64.tar.gz
          test -f out/osdd-linux-arm64.tar.gz
          test -f out/osdd-darwin-amd64.tar.gz
          test -f out/osdd-darwin-arm64.tar.gz
          test -f out/osdd-windows-amd64.zip
          test -f out/osdd-windows-arm64.zip
          test -f out/checksums.txt
          echo "All archives and checksums present."

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          draft: false
          prerelease: false
          files: |
            out/osdd-*.tar.gz
            out/osdd-*.zip
            out/checksums.txt
          body: |
            ### OpenSDD CLI ${{ inputs.version }}

            Download the appropriate archive for your platform:
            - Linux (amd64): `osdd-linux-amd64.tar.gz`
            - Linux (arm64): `osdd-linux-arm64.tar.gz`
            - macOS (amd64): `osdd-darwin-amd64.tar.gz`
            - macOS (arm64): `osdd-darwin-arm64.tar.gz`
            - Windows (amd64): `osdd-windows-amd64.zip`
            - Windows (arm64): `osdd-windows-arm64.zip`

            Verify version:
            - Linux/macOS:
              1) `tar -xzf osdd-<os>-<arch>.tar.gz`
              2) `chmod +x ./osdd-<os>-<arch>`
              3) `./osdd-<os>-<arch> version`
            - Windows:
              1) `unzip osdd-windows-<arch>.zip` (or use File Explorer to extract)
              2) `./osdd-windows-<arch>.exe version`

            Checksums:
            - A `checksums.txt` file is attached containing SHA-256 sums for all archives.
            - Verify on Linux/macOS: `shasum -a 256 -c checksums.txt | grep osdd-<os>-<arch>`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
